services:
  - type: web
    name: jotips
    env: node
    branch: master
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_TOKEN
        value: jotips2024
